version: "3.8"
services:
  app:
    build: .
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    environment:
      BUNDLE_GEMFILE: /app/Gemfile
    command: script/docker-dev-start-web.sh
    ports:
      - "3000:3000"
